
#
# (C) Copyright 1999 Denis McLaughlin
#

###########################################################################'
# This file is automatically generated by the makescripts/h2pl script

$clubs=0;
$diamonds=1;
$hearts=2;
$spades=3;

###########################################################################'
1;

